# Generated by Django 4.0.3 on 2023-07-25 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='testnum',
        ),
    ]
