# Generated by Django 4.0.3 on 2023-07-25 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0002_remove_problem_answer_remove_problem_testnum'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='testnum',
            field=models.IntegerField(default=1),
        ),
    ]
